### ISSUE TITLE
firmware 8.3.0.0A_201912271707

### ISSUE THREAD

**Issue by larsvandoremalen** [roleoroleo/yi-hack-Allwinner#146] opened 2020-09-13 17:29 UTC
Just tried to use this on a 9FUSY32KOU7XL7200319 with firmware  8.3.0.0A_201912271707 but the connection is refused when trying to connect to the camera IP. Tried to downgrade to 8.2 firmware and thought I bricked it for a moment but using the unhack archive it is back to stock. 

Does anybody  have any pointers on how to make this work on 8.3 firmware or did I just do something wrong?

Thanks!

**Comment by roleoroleo** [comment] 2020-09-13 19:46
I think 8.3.0 isn't a new fw but a different cam.

**Comment by larsvandoremalen** [comment] 2020-09-13 21:38
ha anyway to find that out for sure and/or which chipset is being used, without a serial connection? Otherwise I should have a ttl32 lying around somewhere but will have to search a few boxes. Thanks for thelp, much obliged!

**Comment by roleoroleo** [comment] 2020-09-14 07:19
You could try if this procedure works:
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by larsvandoremalen** [comment] 2020-09-14 11:01
yeah that works, did that directly after I recovered. You can find the files here (except mtdblock7 which is a 0kb file ): https://filebin.net/msnx5yok8b0tz624

**Comment by roleoroleo** [comment] 2020-09-14 17:13
Your cam is a y25ga.
The support is experimental, committed but not released.
https://github.com/roleoroleo/yi-hack-Allwinner/commit/4056f62afcc1060bfdfcb84ff8f484d7056111c0

**Comment by larsvandoremalen** [comment] 2020-09-14 17:42
That is really great, shall I wait for release or would you like me to test a dev version?

**Comment by roleoroleo** [comment] 2020-09-14 18:29
Here you can find a dev version:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/132#issuecomment-681915209

**Comment by larsvandoremalen** [comment] 2020-09-15 10:36
ok  I have flashed the dev version from the other thread. Still refuses web connections although I am able to connect a telnet client and run pings on it. Anything I can do to help resolve?

**Comment by roleoroleo** [comment] 2020-09-15 10:42
Post a `ps` command and `la -laR /` command.

**Comment by larsvandoremalen** [comment] 2020-09-15 11:21
sure see txt file attached, the ls command was too long to paste here. 
[commands.txt](https://github.com/roleoroleo/yi-hack-Allwinner/files/5224477/commands.txt)

**Comment by roleoroleo** [comment] 2020-09-15 18:49
Which archive did you use to apply the hack?

**Comment by larsvandoremalen** [comment] 2020-09-15 20:16
I used the file you posted in issue 132 and copied all the contents of the tar to the SD file: 
![image](https://user-images.githubusercontent.com/60351810/93260047-17d74280-f7a1-11ea-9b32-c66de9ada93c.png)

**Comment by roleoroleo** [comment] 2020-09-16 06:03
The hack is ok but the archive is not installed.

**Comment by larsvandoremalen** [comment] 2020-09-16 10:01
Ok did that and the light is on orange for a few seconds and it does a restart, connects to wifi properly (flashing blue then continuous blue)(log is written to sd card) but it still refuses connections to the ip adress from either pc or the yi app for that matter.

**Comment by jempo** [comment] 2020-09-25 17:19
Hi All, i've the same issue for the same FW. Does anyone have an update about this model?
Many Thanks

**Comment by roleoroleo** [comment] 2020-09-26 10:30
I need to check again the update procedure.
I think there is a problem with the name of the file.

**Comment by mleon0304** [comment] 2020-09-27 04:20
Hello!

Can you describe how you're trying to connect to your camera?? e.g. http://192.168.3.44         ???

**Comment by jempo** [comment] 2020-09-27 06:58
Hi @mleon0304, sure. It's the same method described from @larsvandoremalen in previous post and in the README of the project.
I'm trying to connect to http://IP:8080 or with the Yi Application after the hack, but both are unresponsive with the hack. Reverting the hack with the procedure [Unbrick the hack](https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Unbrick-the-cam) all return normal and camera connect to Yi Application.

**Comment by roleoroleo** [comment] 2020-09-27 08:22
After the upgrade, what's the extension of the file home_y25gam?
stage? done? Or nothing?

**Comment by jempo** [comment] 2020-09-27 15:01
Hi @roleoroleo, i'm using the archive posted in this [thread](https://github.com/roleoroleo/yi-hack-Allwinner/issues/132#issuecomment-681915209).
Th archive have `home_y25gam.stage` file, after flash the file was without extension.
In the screenshot the situation after flash. 
Do you need more info?

![Schermata 2020-09-27 alle 17 01 08](https://user-images.githubusercontent.com/5411098/94368150-0b2ce580-00e3-11eb-8886-5286e1a581f6.png)

**Comment by roleoroleo** [comment] 2020-09-27 18:51
If the extension isn't .done the upgrade process is not completed successfully.

**Comment by roleoroleo** [comment] 2020-09-27 19:41
Telnet works. It's true.
Try to run ls and post the output.
```
ls -laR
```

**Comment by jempo** [comment] 2020-09-28 05:09
Yes, telnet works. The LS command of `/root` folder is this.

`
drwxrwxr-x    2 root     root            30 Nov 25  2019 .
drwxrwxr-x   14 root     root           195 Nov 25  2019 ..
-rw-rw-r--    1 root     root             0 Nov 25  2019 topfile
`
Did you need about other folder?

**Comment by roleoroleo** [comment] 2020-09-28 07:32
```
ls -laR /
```

**Comment by jempo** [comment] 2020-09-28 07:39
Thanks :) ok here in the attachment the output.
[ls.log](https://github.com/roleoroleo/yi-hack-Allwinner/files/5290638/ls.log)

**Comment by roleoroleo** [comment] 2020-09-28 09:54
I checked your file system and I can confirm that the hack works but the update procedure doesn't start.
I don't know how to fix the problem without a cam.

**Comment by jempo** [comment] 2020-09-28 11:50
Ok @roleorole, thanks for your help! I don't know if there is a debug procedure when camera flashing the hack. Maybe with more logs we can find the problem.

**Comment by roleoroleo** [comment] 2020-09-28 12:21
Yes.
We could try to add some log to the /home/app/init.sh file where there the procedure starts:
```
...
elif [ -f /tmp/sd/home_y25gam ]; then
    echo "---tmp/sd/home_y25gam exist, update begin---"
    dd if=/tmp/sd/home_y25gam of=/tmp/newver bs=22 count=1
    newver=$(cat /tmp/newver)
...
```
And to the file /home/base/tools/extpkg.sh

**Comment by jempo** [comment] 2020-09-28 13:18
Ok but i don't have understand where are the `/home/app/init.sh`. Also, what we need to log? and were are placed the logs?

**Comment by jempo** [comment] 2020-09-28 17:29
ok thanks, but i see that in the init.sh in tha camera there is only mention about the model `home_y20gam` and not the `home_y25gam`, it's normal?

i post the init.sh from the camera

[init.script.log](https://github.com/roleoroleo/yi-hack-Allwinner/files/5294008/init.script.log)

**Comment by roleoroleo** [comment] 2020-09-28 19:38
Are you sure that you have a 8.3.0 firmware?
You should have home_y25gam label.

**Comment by jempo** [comment] 2020-09-29 05:07
Yeah i'm sure. I've do right now the unhack and checked in the YI Application.
It could be that the unhack change the init.sh? Because it's strange also for me that there is the home_y20gam in my init.sh if the model is y25..
![IMG_155F6C164F7A-1](https://user-images.githubusercontent.com/5411098/94514717-3538f180-0222-11eb-84b3-fc230214e38d.jpeg)

**Comment by roleoroleo** [comment] 2020-09-29 06:46
Yes, if you used the released unhack procedure, now you have the wrong init.sh.
The unhack procedure is only for y20 model, at the moment.
I will create a new unhack for y25 model and I will send you.

**Comment by jempo** [comment] 2020-09-29 06:53
Ok many thanks, i wait for the new unhack :)

**Comment by roleoroleo** [comment] 2020-09-29 06:58
They are almost the same.

Here it is:
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Remove-the-hack

**Comment by jempo** [comment] 2020-09-29 07:05
Ok the new unhack works, now returning to the logs, there is some preferred point in the init.sh that can i put the log to see what goes wrong in the update?

**Comment by roleoroleo** [comment] 2020-09-29 07:14
I think update should work now.

**Comment by jempo** [comment] 2020-09-29 07:47
Ohh yeah! it works! Many Thanks @roleoroleo 🥇  
I don't know what is your release schedule, but the y25 hack works for me now :)

![Schermata 2020-09-29 alle 09 44 34](https://user-images.githubusercontent.com/5411098/94528372-966bbf80-0238-11eb-90e2-c52238d02d8e.png)

**Comment by aidalover** [comment] 2020-10-03 11:22
> I think update should work now.

hi, i also have a 9FUSY32 with firmware 8.3.0.0A_201912271707. where can i find a link to the working hack or are you gonna start it in a new project? thanks....

**Comment by roleoroleo** [comment] 2020-10-03 11:39
In the release page.

**Closed** 2020-11-21 19:13 UTC

**Comment by ykhandler** [comment] 2020-12-20 23:17
> yeah that works, did that directly after I recovered. You can find the files here (except mtdblock7 which is a 0kb file ): https://filebin.net/msnx5yok8b0tz624

@larsvandoremalen, can you please send me the mtdblock0 to mtdblock4, i got 1 camera stuck. Thanks.
