### ISSUE TITLE
update to 0.1.5 leads to invalid option in system.conf

### ISSUE THREAD

**Issue by skdnp** [roleoroleo/yi-hack-Allwinner#33] opened 2020-05-13 08:49 UTC
Hello.

Performing the update from 0.1.4 to 0.1.5 via the web interface left behind the line
DISABLE_CLOUD=&PASSWORD
in system.conf for me. I can't tell what it was before while on 0.1.4., but probably it was =no.

Somehow this prevented changes made on the configuration page to be saved.
Manually changing the setting system.conf via ssh fixed this for me.

**Comment by roleoroleo** [comment] 2020-05-13 09:11
Other users reported the same problem.

**Comment by crdnl** [comment] 2020-05-22 07:42
Closing as duplicate of #24

**Closed by crdnl** 2020-05-22 07:42 UTC
Labels: bug
