### ISSUE TITLE
New YI Home 1080P AI+ BFUSY44GEE with FW 9.0.19.02_202007141512 supported?

### ISSUE THREAD

**Issue by RestOp** [roleoroleo/yi-hack-Allwinner#157] opened 2020-09-30 19:29 UTC
Hello,
New YI Home 1080P AI+ BFUSY44GEE with FW 9.0.19.02_202007141512
I just got this cam https://www.amazon.es/gp/product/B01MR82NFZ
On the back side of Cam is BFUSY44GEE. Date on box 2020.09
I made a backup of FW. Here it is: https://drive.google.com/drive/folders/1ifFIDG4G0v-aIKrE_4kcy3elXd5Bsae3
Can not understand if it is supported or not. Could you please look and say if I need to send it back to amazon?

Thanks a lot!

**Comment by danielk117** [comment] 2020-10-02 18:20
Same here... BFUSY44*** and firmware 9.0.19.02_202007141512, bought on amazon germany.

**Comment by lassieee** [comment] 2020-10-03 07:37
me too. Got mine yesterday from amazon:
firmware 9.0.19.02_202007141512
DID: BFUS440PE...
SN: BY21GAEUW...
not sure if there's a hacked firmware for this model already.

![IMG_20201003_091236](https://user-images.githubusercontent.com/4531126/94986072-e8278900-055b-11eb-8f3c-b7e40e129034.jpg)
![IMG_20201003_091630](https://user-images.githubusercontent.com/4531126/94986074-e9f14c80-055b-11eb-8a62-be76e41472d7.jpg)

**Comment by danielk117** [comment] 2020-10-03 08:45
Thanks for the teardown images 👍 
I tought these internal model names (like y20ga) came from the DID, but your board is marked as y29ga...

I think there isnt a hacked firmware for this device, because its just too new. But the QG2101A isnt new at all (see #70).
I hope @roleoroleo can tell if it belongs to MStar or Allwinner.

**Comment by RestOp** [comment] 2020-10-03 08:47
I hope also, in other way it must be send back to amazon 😌 I do need this cam if i can not intergrate it in HA 😀

**Comment by danielk117** [comment] 2020-10-03 11:51
> Guys, have you found any alternative to these cams in same price?
No...

**Comment by roleoroleo** [comment] 2020-10-03 14:13
I think it's an Allwinner model.
But the flash partitions are different.
home is a read only squashfs.
A new hack is needed.

**Comment by RestOp** [comment] 2020-10-03 16:43
> I think it's an Allwinner model.
> But the flash partitions are different.
> home is a read only squashfs.
> A new hack is needed.

It means we can forget and send it back or any chances in visible future?🤪

**Comment by roleoroleo** [comment] 2020-10-03 17:23
Moreover, the flash size is 8MB and not 16MB like the "current" Allwinner.
I think that the hack is possible but only using the external SD.

**Comment by roleoroleo** [comment] 2020-10-03 17:28
See here:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/105

Same hardware.

**Comment by lassieee** [comment] 2020-10-03 17:32
Sounds like a starting point. I wish I had the tools and skills to help in any way. If there is anything you think I could help with, please let me know!

**Comment by danielk117** [comment] 2020-10-03 19:41
> home is a read only squashfs.
> A new hack is needed.

You mean we need a root for this model? 
A a new hacks sounds like weeks or months, if anything is coming.

@RestOp Alternative in same price? I bought a 4pack of these cams on amazon germany just two week sago. All cams are 9FUS und flashable with this allwinner hack. But all cams have a disturbing noise coming trough the microphone (before and after hacking). So I wanted to send them back and bought new single ones (the new unknown model 😞).

**Comment by roleoroleo** [comment] 2020-10-03 21:31
Analyzing the file init.sh probably we could create an hack, like the Allwinner model.
But without a cam, I can't do it.

**Comment by roleoroleo** [comment] 2020-10-04 07:56
init.sh contains the same hack:
```
if [ -f "/tmp/sd/Factory/factory_test.sh" ]; then
        /tmp/sd/Factory/config.sh
        exit
fi
```
I could try to create a new telnet hack.

**Comment by lassieee** [comment] 2020-10-04 08:08
First of all thank you very much for your time and effort Roleo, it's much appreciated! 
I can imagine you really do need one of these new cams to create a successful hack, so perhaps we could:
A) see how many people are interested and split the cost so you can buy one of these cams to hack it, without any guarantees
B) I could send you my cam by mail and when you're done with it, you can return it
C) try to explain how the hacking procedure goes. I lack (proper) smd skills and jtag tools, but I'm a Linux engineer so I'm not completely clueless, and I can do some really simple soldering too.

**Comment by roleoroleo** [comment] 2020-10-04 08:33
I think I could start without a cam.
Then, if necessary, A would be the best.
In the meantime, if someone wants to try ...
[y21_hack.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5322868/y21_hack.tar.gz)

**Comment by danielk117** [comment] 2020-10-04 08:57
@roleoroleo I will give a try 😉

**Comment by danielk117** [comment] 2020-10-04 09:25
Factory was renamed to Factory.done, but no telnet

**Comment by roleoroleo** [comment] 2020-10-04 09:53
So, the script is executed but telnet doesn't start.

**Comment by RestOp** [comment] 2020-10-04 09:56
> So, the script is executed but telnet doesn't start.

What does it means? No way to hack?

**Comment by roleoroleo** [comment] 2020-10-04 10:17
No, no...
The hack s possible.

**Comment by roleoroleo** [comment] 2020-10-04 11:18
Ok. try this:
[y21_hack.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5323074/y21_hack.tar.gz)

**Comment by lassieee** [comment] 2020-10-04 11:31
Factory has been renamed to Factory.done, contains the file lower_half_init.sh which contains '/usr/sbin/telnetd &' (same as with your previous tar). Unfortunately nothing listens on port 23.
I was wondering if there is a telnetd in /usr/sbin, so i tried to ls -l /usr/sbin > /tmp/sd/Factory/sbin.txt but sbin.txt doesn't get created.

**Comment by lassieee** [comment] 2020-10-04 11:35
wait, scratch that, i reformatted my sd card and tried again, i got a telnet prompt now!

**Comment by roleoroleo** [comment] 2020-10-04 12:18
Ok.
Now the long part.

1. We need to create a new repo
2. Copy the Allwinner tree
3. Change all programs moving the binary from /home/yi-hack/ to /tmp/sd/yi-hack/
4. Check if h264grabber works or the framebuffer structure is changed
5. Check all compiled programs
6. ...

**Comment by RestOp** [comment] 2020-10-04 12:22
Unfortunatly, i'm not linux-friendly, but i'm study-friendly😎 so if any help from me needed, let me know!

**Comment by lassieee** [comment] 2020-10-04 12:31
Cool! If I can help in any way, please let me know :-)

**Comment by danielk117** [comment] 2020-10-04 13:31
Great 👍🏻 Will try it tonight 😊

**Comment by roleoroleo** [comment] 2020-10-04 15:15
I'm starting to create the new repo.
And effectiverly, without a cam it is very difficult. I can't ask you to try a new fw every 5 minutes.
Probably I need a cam...

**Comment by RestOp** [comment] 2020-10-04 15:20
> I'm starting to create the new repo.
> And effectiverly, without a cam it is very difficult. I can't ask you to try a new fw every 5 minutes.
> Probably I need a cam...

Understand, maybe u can try to make few different revisions and we will try them all and comment behavior?

**Comment by roleoroleo** [comment] 2020-10-04 17:28
This is the final (at the moment) version of the hack.
It overwrites /backup/init.sh with a "better" version that runs a shell script on the sd card at the end of the procedure.
If you install this hack you could start a new firmware on sd . If you remove the sd, the cam starts with the original fw.
[y21ga_hack.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5323799/y21ga_hack.tar.gz)

**Comment by danielk117** [comment] 2020-10-04 18:01
Works 👍 Im able to connect via telnet.

> If you install this hack you could start a new firmware on sd . If you remove the sd, the cam starts with the original fw.

What exactly do mean with "start a new firmware on sd"? 

Just unpack your latest home_y20gam.stage, copy all files from /home/yi-hack/ to /SDCARD/yi-hack/ and edit all paths in your bash scripts to the new path?

**Comment by roleoroleo** [comment] 2020-10-04 18:48
> What exactly do mean with "start a new firmware on sd"?

Wrong sentence.
It starts all additional programs.

> Just unpack your latest home_y20gam.stage, copy all files from /home/yi-hack/ to /SDCARD/yi-hack/ and edit all paths in your bash scripts to the new path?

It's not enough.
I have to change all the compilation/installation path.

**Comment by danielk117** [comment] 2020-10-04 19:00
Ok, tried it anyway 
[system.log](https://github.com/roleoroleo/yi-hack-Allwinner/files/5324119/system.log)

**Comment by pep4n** [comment] 2020-10-05 18:06
+1 for this. 

DID: BFUSY44...
SN_: BY21GAEU... 
FW: 9.0.19.02_202007141512

Let me know if I can test or support. 
Beer was just ordered ,) 
_Transaction ID: 8C490144TB577435B_

**Comment by roleoroleo** [comment] 2020-10-05 18:09
I'm working on it.
It will be a new repo.

**Comment by roleoroleo** [comment] 2020-10-06 05:55
I finished a first alpha release:
[y21ga_0.0.1.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5331644/y21ga_0.0.1.tar.gz)
Simply decompress it on your sd card.

Try it and give me a feedback.
In the meantime I will create the repo.

**Comment by lassieee** [comment] 2020-10-06 06:35
a little donation to get you started on that new cam: Transaction ID: 13M381272E579543T

**Comment by roleoroleo** [comment] 2020-10-06 06:40
> Beer was just ordered ,)
> _Transaction ID: 8C490144TB577435B_

> a little donation to get you started on that new cam: Transaction ID: 13M381272E579543T

@pep4n @lassieee 
Thank you!

**Comment by lassieee** [comment] 2020-10-06 07:02
FAT filesystem doesn't support symlinks :-(
The camera does need FAT, right?

**Comment by roleoroleo** [comment] 2020-10-06 07:05
Right.
I took this into consideration when I compiled busybox but there are probably other points...
For example yi-hack-v4 is a symlink, mqttv4 will not work (at the moment).

**Comment by roleoroleo** [comment] 2020-10-06 12:52
Removed all the symlinks:
[y21ga_0.0.2.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5333848/y21ga_0.0.2.tar.gz)

**Comment by lassieee** [comment] 2020-10-06 14:34
sweet! I've been fiddling with this as well. I thought maybe we could add a script, or some lines to an existing script, that lets busybox on the camera make the symlinks, but it's been a busy day lol
I'll give this latest version a try and let you know

**Comment by roleoroleo** [comment] 2020-10-06 15:32
system.sh should start automatically.
You don't have to run it (if the procedure works).
Check if the processes are runnings: httpd, ftpdf, mqttv4, etc...

**Comment by roleoroleo** [comment] 2020-10-06 15:48
If you need the unhack procedure to remove the hack:
[unhack_y21ga.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5335076/unhack_y21ga.tar.gz)

**Comment by danielk117** [comment] 2020-10-06 16:15
> If you need the unhack procedure to remove the hack:
> [unhack_y21ga.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5335076/unhack_y21ga.tar.gz)

The LED remains orange. No matter if with or without SD card.

**Comment by roleoroleo** [comment] 2020-10-06 16:23
Very strange.

**Comment by danielk117** [comment] 2020-10-06 16:30
The camera does nothing except the orange LED.

**Comment by roleoroleo** [comment] 2020-10-06 16:44
Apply again the hack.

**Comment by lassieee** [comment] 2020-10-06 16:50
> system.sh should start automatically.
> You don't have to run it (if the procedure works).
> Check if the processes are runnings: httpd, ftpdf, mqttv4, etc...
> 
> EDIT
> 
> Found the problem...
> One more time around the block.
> [y21ga_0.0.2.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5334974/y21ga_0.0.2.tar.gz)

I have no processes like httpd or ftpd running. I also can't find a binary for httpd. I've read that's part of busybox, but I'm unable to start if from a little test script. It says httpd not found.
I'm such a busybox n00b lol

**Comment by danielk117** [comment] 2020-10-06 17:29
> Apply again the hack.

Nothing happend. Factory isnt renamed anymore. I think its bricked.

**Comment by roleoroleo** [comment] 2020-10-06 17:50
> Nothing happend. Factory isnt renamed anymore. I think its bricked.

Did you clean the sd?
Is telnetd running?

**Comment by roleoroleo** [comment] 2020-10-06 17:59
> I have no processes like httpd or ftpd running. I also can't find a binary for httpd. I've read that's part of busybox, but I'm unable to start if from a little test script. It says httpd not found.
> I'm such a busybox n00b lol

I thought httpd was in the original busybox, but it's not there.
I will add it.

**Comment by lassieee** [comment] 2020-10-06 18:28
thanks. Can you also add hostname? that's missing as well

**Comment by roleoroleo** [comment] 2020-10-06 18:35
0.0.3: httpd and hostname
Please let me know if httpd starts.
[y21ga_0.0.3.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5335952/y21ga_0.0.3.tar.gz)

**Comment by roleoroleo** [comment] 2020-10-06 18:37
@danielk117 
This is the unbrick procedure for the older model:
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Unbrick-the-cam
I think it's pretty the same.
But you have to restore mtdblock4.

If you are able to connect the uart with a usb-serial adapter I can help you.

**Comment by lassieee** [comment] 2020-10-07 05:59
Ok, found it. In a previous version, we didn't have httpd so httpd couldn't start. Adding telnetd to /backup/init.sh DID work, so the check in Factory/config.sh skips copying newbackup/init.sh to /backup/init.sh because the hack is supposedly already in place.
httpd is running! 
![Screenshot from 2020-10-07 07-55-00](https://user-images.githubusercontent.com/4531126/95292983-de12cc80-0872-11eb-915d-d8b8df4b3bd9.png)

**Comment by roleoroleo** [comment] 2020-10-07 07:16
Good!!!
This result is better than all my expectations.


> Ok, found it. In a previous version, we didn't have httpd so httpd couldn't start. Adding telnetd to /backup/init.sh DID work, so the check in Factory/config.sh skips copying newbackup/init.sh to /backup/init.sh because the hack is supposedly already in place.
> httpd is running! and so is ftpd, rstp..

Ok, new users shouldn't have this problem.

/tmp/sd/record:
Fixed removing the ln command from compile.www
Try to remove the symlink and it should work.
init.sh creates a bind mount.

Serial number:
The command (inside status.json cgi) is
SERIAL_NUMBER=$(dd bs=1 count=20 skip=592 if=/tmp/mmap.info 2>/dev/null | cut -c1-20)
dd and cut are present, probably the mmap.info file is different. Actually is offset=592, len=20
Check your mmap.info.

Memory:
free command is missing, I will add it in the next release.

Please check if rtsp stream is running and if the snapshot service works.
The 2 most complicated pieces.

**Comment by danielk117** [comment] 2020-10-07 07:59
> @danielk117
> This is the unbrick procedure for the older model:
> https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Unbrick-the-cam
> I think it's pretty the same.
> But you have to restore mtdblock4.
> 
> If you are able to connect the uart with a usb-serial adapter I can help you.

I think this happend because i have the first hack installed (with the modified lower_half_init.sh and so on). 
Yes, I'm able to connect to uart (i own a TTL-interface and on @lassieee photos I see at least a RX, so there will probably be a marked TX too).
I'm still deciding whether to unscrew the device and destroy the warranty seal or just send the camera back (and hope that Amazon simply writes the device off as defective). 🙄

**Comment by roleoroleo** [comment] 2020-10-07 08:27
Ok, let me know if you need help.
I'm sorry about that.

**Comment by pep4n** [comment] 2020-10-07 08:28
> 
> 
> > @danielk117
> > This is the unbrick procedure for the older model:
> > https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Unbrick-the-cam
> > I think it's pretty the same.
> > But you have to restore mtdblock4.
> > If you are able to connect the uart with a usb-serial adapter I can help you.
> 
> I think this happend because i have the first hack installed (with the modified lower_half_init.sh and so on).
> Yes, I'm able to connect to uart (i own a TTL-interface and on @lassieee photos I see at least a RX, so there will probably be a marked TX too).
> I'm still deciding whether to unscrew the device and destroy the warranty seal or just send the camera back (and hope that Amazon simply writes the device off as defective). 🙄

I would recommend to send it back as DOA. 
Usually they don't check returns less than 40€.

**Comment by lassieee** [comment] 2020-10-07 10:05
> Good!!!
> This result is better than all my expectations.
> 
> > Ok, found it. In a previous version, we didn't have httpd so httpd couldn't start. Adding telnetd to /backup/init.sh DID work, so the check in Factory/config.sh skips copying newbackup/init.sh to /backup/init.sh because the hack is supposedly already in place.
> > httpd is running! and so is ftpd, rstp..
> 
> Ok, new users shouldn't have this problem.
> 
> /tmp/sd/record:
> Fixed removing the ln command from compile.www
> Try to remove the symlink manually and it should work.
> init.sh creates a bind mount.
> 
> Serial number:
> The command (inside status.json cgi) is
> SERIAL_NUMBER=$(dd bs=1 count=20 skip=592 if=/tmp/mmap.info 2>/dev/null | cut -c1-20)
> dd and cut are present, probably the mmap.info file is different. Actually is offset=592, len=20
> Check your mmap.info.
> 
> Memory:
> free command is missing, I will add it in the next release.
> 
> Please check if rtsp stream is running and if the snapshot service works.
> The 2 most complicated pieces.

I need some more time to test, but it's a busy day today.
tail is missing. adding it from a busybox:1.27.2 container doesn't work. how do you add these?
both rtsp stream and snapshot do not work. i tried killing the wd_rtsp.sh script and running rRTSPServer in debug mode, and it seems I can connect with vlc player, but i have no image.

`root@(none):/tmp/sd/yi-hack/script# rRTSPServer -d
debug on
mapping file /dev/shm/fshare_frame_buf, size 1786156, to b6c1c000
closing the file /dev/shm/fshare_frame_buf
starting capture main loop

"ch0_0.h264" stream, from memory
Audio enabled
Play this stream using the URL "rtsp://<ip_addr>/ch0_0.h264"

"ch0_2.h264" stream, from memory
Audio enabled
Play this stream using the URL "rtsp://<ip_addr>/ch0_2.h264"
`

**Comment by roleoroleo** [comment] 2020-10-07 12:36
> tail is missing. adding it from a busybox:1.27.2 container doesn't work, i get the error "/tmp/sd/yi-hack/bin/tail: line 1: syntax error: unexpected "("" . how do you add these?

There are 2 different busybox. The first one is the original bb and is on the read only rootfs partitions.
The second one (added by this project) is on the sd card and we can change it.
I will add tail.

> both rtsp stream and snapshot do not work.
> after killing the wd_rtsp.sh scrint and runngin it manually: Failed to create RTSP server: bind() error (port number: 554): Address in use. It seems as if it keeps restarting.

When you receive this message, wait 30 seconds and try again.

> i tried killing the wd_rtsp.sh script and running rRTSPServer in debug mode, and it seems I can connect with vlc player, but i have no image.

Probably the problem is h264grabber. We need to study the framegrabber file.

> /tmp/mmap.info does not contain my serial number, at least not my SN that's on the box (this file does contain my DID though). I'll check later if i can find a file which has my SN in it.

Ok.

**Comment by danielk117** [comment] 2020-10-07 16:24
> Ok, let me know if you need help.
> I'm sorry about that.
 
No problem, I am aware of the risk that the camera could break. 😉

**Comment by roleoroleo** [comment] 2020-10-07 20:20
https://github.com/roleoroleo/yi-hack-Allwinner-v2
Please contribute.

**Comment by RestOp** [comment] 2020-10-09 13:50
Hello,

> https://github.com/roleoroleo/yi-hack-Allwinner-v2
> Please contribute.

Have i understood right, that we can already try to install new FW?
But on the link 

![image](https://user-images.githubusercontent.com/46259141/95590921-f6d3db80-0a46-11eb-9a16-d3867fd5a107.png)

i got old repository 

![image](https://user-images.githubusercontent.com/46259141/95590974-06532480-0a47-11eb-8d61-d2c5cba024c5.png)

So where could i find new FW?

**Comment by pep4n** [comment] 2020-10-09 13:59
It's WIP and no release was built yet.

Am Fr., 9. Okt. 2020 um 15:50 Uhr schrieb RestOp <notifications@github.com>:

**Comment by roleoroleo** [comment] 2020-10-09 14:32
The link https://github.com/roleoroleo/yi-hack-Allwinner-v2 is ok.
The readme is not updated.

At the moment the hack is not enough stable to create a release.

**Comment by roleoroleo** [comment] 2020-10-09 14:36
Please, continue this thread here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/3

**Closed** 2020-11-21 19:21 UTC

**Comment by lohacker84** [comment] 2022-12-13 13:06
hi good morning I would need you to send me the firmware 9.0.19.02_202007141512 as since I updated to the firmware New y21ga_9.0.19.12_202102241808 everything is blurry at night.  I hope you can help me because this really does not look good

**Comment by Jaragar** [comment] 2024-07-29 19:38
> Hello, New YI Home 1080P AI+ BFUSY44GEE with FW 9.0.19.02_202007141512 I just got this cam https://www.amazon.es/gp/product/B01MR82NFZ On the back side of Cam is BFUSY44GEE. Date on box 2020.09 I made a backup of FW. Here it is: https://drive.google.com/drive/folders/1ifFIDG4G0v-aIKrE_4kcy3elXd5Bsae3 Can not understand if it is supported or not. Could you please look and say if I need to send it back to amazon?
> 
> Thanks a lot!
Hi could you send me a copy of the full firmware I would like to do some work with it and see if I can use it to create a new hack. 
 planetciencia2000@gmail.com
